config/routes.rb
Rails.application.routes.draw do

  get 'questions/create'
  get 'questions/edit'
  get 'questions/update'
  get 'questions/destroy'
  root 'users#index'
  
  resources :users, except: [:destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]

  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  MAX_LENGTH = 255

  belongs_to :user

  validates :text, :user, presence: true
  validates :text, length: { maximum: MAX_LENGTH }
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  MAX_LENGTH = 40
  EMAIL_REGEX = URI::MailTo::EMAIL_REGEXP
  USERNAME_REGEX = /\A[a-zA-Z0-9_]+\z/
  #параметры работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  before_validation :normalize_name, on: :create

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: EMAIL_REGEX }

  validates :username,
            presence: true,
            uniqueness: true,
            length: { maximum: MAX_LENGTH },
            format: { with: USERNAME_REGEX }

  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_save :encrypt_password

  def encrypt_password
    if self.password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

  private
    def normalize_name
      self.username = username.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def load_question
    @question ||= Question.find(params[:id])
  end

  def question_params
    if current_user.present? && params[:question][:user_id] == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный email или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы разлогинились. Приходите еще!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :new, :create]

  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  def new
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'Пользователь успешно зарегистрирован!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :username, :avatar_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.gif'
    end
  end

  def sklon_noun(word, quantity)
    last_digit = quantity.to_s.split('').last.to_i

    if quantity > 10
      last_digit_11_14 = (quantity.to_s.split('')[-2] + quantity.to_s.split('').last).to_i
    else
      last_digit_11_14 = 0
    end

    if last_digit_11_14 > 10 && last_digit_11_14 < 15
      "#{word[2]}"
    elsif last_digit == 1
      "#{word[0]}"
    elsif last_digit > 1 && last_digit < 5
      "#{word[1]}"
    else
      "#{word[2]}"
    end
  end

  def sklon_adj(word, quantity)
    last_digit = quantity % 10

    if last_digit == 1
      "#{word[0]}"
    else
      "#{word[1]}"
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
        </div>

        <div class="header-nav">
          <% if current_user %>
            <%= link_to "@#{current_user.username}", user_path(current_user) %>
            <%= link_to 'Выйти', log_out_path %>
          <% else %>
            <%= link_to 'Зарегистрироваться', sign_up_path, class: 'button button-light button-small' %>
            <%= link_to 'Войти', log_in_path, class: 'button button-light button-small' %>
          <% end %>
        </div>

      </div>
    </div>

    <div class="content">
      <div class="container">
        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/questions/_form.html.erb
<div class="form">
	<%= form_for @question do |f| %>
		<% if @question.errors.any? %>
	      <div class="form-errors">
	      	<ul>
	            <% @question.errors.full_messages.each do |message| %>
	              <%= content_tag :li, message, class: 'form-error-message' %>
	            <% end %>
	    	</ul>
	      </div>
	    <% end %>

	    <%= f.hidden_field :user_id %>

		<div class="form-field">
			<%= f.label :text, 'Вопрос', class: 'form-label' %>
			<%= f.text_area :text, class: 'form-textarea' %>
		</div>

		<% if current_user.present? && current_user == @question.user %>
			<div class="form-field">
				<%= f.label :answer, 'Ответ', class: 'form-label' %>
				<%= f.text_area :answer, class: 'form-textarea' %>
			</div>
		<% end %>

		<div class="form-action buffer-both">
			<%= f.submit 'Сохранить', class: 'button button-small button-dark' %>
			или
			<%= link_to "вернуться", user_path(@question.user) %>
		</div>
	<% end %>
</div>

app/views/questions/_question.html.erb
<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>

<div class="question">
	<div class="question-content">
		<div class="question-text text-lead">
			<%= question.text %>
		</div>

		<% if question.answer.present? %>
			<div class="question-answer text-lead">
				<%= question.answer if question.answer.present? %>
			</div>
		<% end %>

		<div class="question-date">
			<%= l(question.created_at, format: :short) %>
		</div>

		<% if question.user == current_user %>
			<div class="question-actions">
				<%= link_to fa_icon(action_icon), edit_question_path(question) %>
				<%= link_to fa_icon('trash-o'), question_path(question),
							method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
			</div>
		<% end %>
	</div>
</div>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
	<h1 class="title-medium">Вопрос</h1>

	<div class="column-1-2">
		<%= render 'form' %>
	</div>
</div>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
	<h1 class="title-medium">Править профиль</h1>

	<div class="column-1-2">
		<div class="form">
			<%= form_for @user do |f| %>
				<% if @user.errors.any? %>
		          <div class="form-errors">
		          	<ul>
			            <% @user.errors.full_messages.each do |message| %>
			              <%= content_tag :li, message, class: 'form-error-message' %>
			            <% end %>
		        	</ul>
		          </div>
		        <% end %>

				<div class="form-field">
					<%= f.label :username, 'Никнейм', class: 'form-label' %>
					<%= f.text_field :username, class: 'form-text-field' %>
				</div>

				<div class="form-field">
					<%= f.label :name, 'Имя', class: 'form-label' %>
					<%= f.text_field :name, class: 'form-text-field' %>
				</div>

				<div class="form-field">
					<%= f.label :avatar_url, 'URL вашей аватарки', class: 'form-label' %>
					<%= f.text_field :avatar_url, class: 'form-text-field' %>
				</div>

				<div class="buffer-top-large buffer-bottom">
					Если не хотите менять пароль, оставьте эти поля пустыми!
				</div>

				<div class="form-field">
					<%= f.label :password, 'Пароль', class: 'form-label' %>
					<%= f.password_field :password, class: 'form-text-field' %>
				</div>

				<div class="form-field">
					<%= f.label :password_confirmation, 'Пароль еще раз', class: 'form-label' %>
					<%= f.password_field :password_confirmation, class: 'form-text-field' %>
				</div>

				<div class="form-action">
					<%= f.submit 'Сохранить', class: 'button button-small button-dark' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
	<div class="buffer-both">
		<h1 class="title-medium">Наши пользователи</h1>
	</div>

	<% @users.each do |user| %>
		<div class="users-list-item">
			<div class="user-image-div user-image-div-small">
				<%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
	<h1 class="title-medium">Присоединяйся к нам!</h1>

	<div class="column-1-2">
		<div class="form">
			<%= form_for @user do |f| %>
				<% if @user.errors.any? %>
		          <div class="form-errors">
		          	<ul>
			            <% @user.errors.full_messages.each do |message| %>
			              <%= content_tag :li, message, class: 'form-error-message' %>
			            <% end %>
		        	</ul>
		          </div>
		        <% end %>

				<div class="form-field">
					<%= f.label :email, 'Логин (email)', class: 'form-label' %>
					<%= f.text_field :email, class: 'form-text-field' %>
				</div>

				<div class="form-field">
					<%= f.label :username, 'Никнейм', class: 'form-label' %>
					<%= f.text_field :username, class: 'form-text-field' %>
				</div>

				<div class="form-field">
					<%= f.label :name, 'Имя', class: 'form-label' %>
					<%= f.text_field :name, class: 'form-text-field' %>
				</div>

				<div class="form-field">
					<%= f.label :password, 'Пароль', class: 'form-label' %>
					<%= f.password_field :password, class: 'form-text-field' %>
				</div>

				<div class="form-field">
					<%= f.label :password_confirmation, 'Пароль еще раз', class: 'form-label' %>
					<%= f.password_field :password_confirmation, class: 'form-text-field' %>
				</div>

				<div class="form-action">
					<%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center">
	<h1 class="title-medium">
		<%= @user.name %>
	</h1>

	<div class="buffer-both">
		<%= link_to "Редактировать профиль", edit_user_path(@user) if current_user == @user %>
	</div>

	<div class="user-image-div">
		<%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
	</div>

	<h2 class="title-small buffer-both">
		@<%= @user.username %>
	</h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <%# Выводим счетчики вопросов в три колонки. Обратите внимание, что тут %>
  <%# в пору использовать наш любимый склонятор. На эту тему смотрите ДЗ. %>
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= sklon_noun(['вопрос', 'вопроса', 'вопросов'], @questions_count) %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p><%= sklon_noun(['ответ', 'ответа', 'ответов'], @answers_count) %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p><%= sklon_adj(['безответный', 'безответных'], @unanswered_count) %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id="ask-form">
	<div class="user-question-form buffer-both">
		<div class="form">
			<%= form_for @new_question do |f| %>
				<%= f.hidden_field :user_id %>

				<div class="form-field">
					<%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
					<%= f.text_area :text, class: 'form-textarea' %>
				</div>

				<div class="form-action">
					<%= submit_tag 'Задать вопрос', class: 'button button-green' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<div class="buffer-both">
	<h2 class="title-small" style="color: #fff;">Вам задали <%= sklon_noun(['вопрос', 'вопроса', 'вопросов'], @questions.size) %>!</h2>
</div>

<div class="column-3-4">
	<div class="user-questions buffer-both">
		<div class="questions-list">
			<% @questions.each do |question| %>
				<%= render partial: 'questions/question', object: question %>
			<% end %>
		</div>
	</div>
</div>